# Generated by Django 3.1.7 on 2021-03-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20210314_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes_of_tweet', to='tweets.Like'),
        ),
    ]
